// Stage CesiumJS's runtime static assets into public/cesium/ so Astro serves them
// (verbatim in dev, emitted to dist/ on build) at the '/cesium/' base the cesium-view
// adapter sets as CESIUM_BASE_URL. These are vendored build artifacts, not source, so
// public/cesium/ is gitignored and regenerated by this script — run from `predev` and
// `prebuild` (npm fires those automatically). Only the Globe engine's lazy import pulls
// the Cesium JS bundle; these files are the Workers/Assets/Widgets it then fetches.
import { cp, rm, access } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const from = join(root, 'node_modules', 'cesium', 'Build', 'Cesium');
const to = join(root, 'public', 'cesium');
const DIRS = ['Workers', 'Assets', 'ThirdParty', 'Widgets'];

try {
  await access(from);
} catch {
  console.error(`[copy-cesium] ${from} not found — is the "cesium" package installed?`);
  process.exit(1);
}

await rm(to, { recursive: true, force: true });
for (const dir of DIRS) {
  await cp(join(from, dir), join(to, dir), { recursive: true });
}
console.log(`[copy-cesium] staged ${DIRS.join(', ')} → public/cesium/`);
